# -*- coding: utf-8 -*-
"""NBAProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5KibNLBu50_BXmUdZyAWSQVzRe0-gG5
"""

import pandas as pd
import time

pip install nba_api

from nba_api.stats.endpoints import leaguedashplayerstats, leaguedashplayerbiostats

pergamedata = []
seasons = ['2023-24', '2022-23', '2021-22', '2020-21', '2019-20', '2018-19', '2017-18', '2016-17', '2015-16', '2014-15', '2013-14', '2012-13', '2011-12', '2010-11']

for season in seasons:
  print(f'Fetching {season}...')
  time.sleep(1)

  try:
    stats = leaguedashplayerstats.LeagueDashPlayerStats(season=season, per_mode_detailed='PerGame')
    df = stats.get_data_frames()[0]

    bio = leaguedashplayerbiostats.LeagueDashPlayerBioStats(season=season)
    bio_df = bio.get_data_frames()[0]

    merged = df.merge(bio_df[['PLAYER_ID', 'PLAYER_HEIGHT_INCHES', 'PLAYER_WEIGHT']], on = 'PLAYER_ID', how = 'left')
    merged['SEASON'] = season
    pergamedata.append(merged)
  except Exception as e:
    print(f"Error fetching data for {season}: {e}. Skipping this season.")
    continue

pergame_df = pd.concat(pergamedata, ignore_index = True)
pergame_df = pergame_df[pergame_df['GP'] >= 25]
pergame_df = pergame_df.sort_values(by='GP', ascending=False).drop_duplicates(subset=['PLAYER_ID', 'SEASON'], keep='first')

def calculate_TS(row):
  row['TS%'] = row.PTS / (2 * (row.FGA + 0.44 * row.FTA)) * 100
  return row

pergame_df = pergame_df.apply(calculate_TS, axis = 1)

def calculate_Eff(row):
  row['EFF'] = (1.1 * row.PTS) + row.AST + (0.5 * row.REB) + row.STL + row.BLK - row.TOV - (row.FGA - row.FGM) - (row.FTA - row.FTM)
  return row

def calculate_Pos(row):
  if row.PLAYER_HEIGHT_INCHES < 79.0:
    row['POS'] = 'G'
  elif row.PLAYER_HEIGHT_INCHES < 82.0:
    row['POS'] = 'F'
  else:
    row['POS'] = 'C'
  return row

pergame_df = pergame_df.apply(calculate_Eff, axis = 1)
pergame_df = pergame_df.apply(calculate_Pos, axis = 1)
pergame_df
pergame_df.to_csv('pergame_data_extra.csv', index = False)

#Gives highest eff player in df
max_eff_player = pergame_df.loc[pergame_df['EFF'].idxmax()]
print(max_eff_player[['PLAYER_NAME', 'SEASON', 'EFF']])

#Gives df of specific age and position
pergame_df.loc[(pergame_df.AGE == 39.0) & (pergame_df.POS == 'C')].sort_values(by='EFF', ascending = False)

age_analysis = pergame_df.groupby(['AGE', 'POS']).agg(
    PTS_Avg=('PTS', 'mean'),
    PLUS_MINUS_Avg=('PLUS_MINUS', 'mean'),
    AST_Avg=('AST', 'mean'),
    REB_Avg=('REB', 'mean'),
    TS_Avg=('TS%', 'mean'),
    EFF_Avg=('EFF', 'mean'),
    sample_size=('PLAYER_NAME', 'count')
).round(2)
display(age_analysis.sort_values(by='EFF_Avg', ascending=False))

top_5_efficiencies = pergame_df.groupby(['SEASON', 'POS']).apply(lambda x: x.sort_values(by='EFF', ascending=False).head(5)).reset_index(drop=True)
#display(top_5_efficiencies)
top_age_analysis = top_5_efficiencies.groupby(['AGE', 'POS']).agg(
    PTS_Avg=('PTS', 'mean'),
    PLUS_MINUS_Avg=('PLUS_MINUS', 'mean'),
    TS_Avg=('TS%', 'mean'),
    EFF_Avg=('EFF', 'mean'),
    sample_size=('PLAYER_NAME', 'count')
).round(2)
#print(age_analysis.sort_values(by='EFF_Avg', ascending=False))

player_names = ['Luka Dončić', 'Shai Gilgeous-Alexander', 'Nikola Jokić', 'Karl-Anthony Towns', 'DeMarcus Cousins']
examples_df = pergame_df.loc[pergame_df['PLAYER_NAME'].isin(player_names)]
display(examples_df)

import seaborn as sns

all = sns.lineplot(data = age_analysis, x = 'AGE', y = 'EFF_Avg', hue = 'POS', marker = 'o', linewidth = 1.5)
all.set(title = 'Effeciency Trajectory of the Leage Average at Each Position')

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
good = sns.lineplot(data = top_age_analysis, x = 'AGE', y = 'EFF_Avg', hue = 'POS', marker = 'o')
good.set(title = 'Effeciency Trajectory of Top 5 Players at Each Position')
good.set_ylim(10, 40) # Set a wider range for EFF_Avg

sns.lineplot(data = examples_df, x = 'AGE', y = 'EFF', hue = 'PLAYER_NAME')